FallbackDirectory unicode normalization issue for python3
Need to normalize so both python2 and python3 are happy...

  ======================================================================
  ERROR: test_fallback_directories_from_remote
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python3.2/dist-packages/mock/mock.py", line 1305, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/remote.py", line 193, in test_fallback_directories_from_remote
      fallback_directories = stem.descriptor.remote.FallbackDirectory.from_remote()
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 949, in from_remote
      elif line.startswith('"'):
  TypeError: startswith first arg must be bytes or a tuple of bytes, not str

  ----------------------------------------------------------------------
  Ran 6 tests in 0.018s