Skip tests that rely on netstat and lsof on Gentoo
Some netstat and lsof commands are broken on Gentoo, probably due to restricted
proc permissions. Skipping the tests on that platform...

  ======================================================================
  ERROR: test_pid_by_port_lsof
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/system.py", line 332, in test_pid_by_port_lsof
      self.assertEquals(tor_pid, stem.util.system.pid_by_port(test.runner.CONTROL_PORT))
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/system.py", line 536, in pid_by_port
      results = call(GET_PID_BY_PORT_LSOF, None)
    File "/usr/lib64/python2.7/site-packages/mock.py", line 964, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/usr/lib64/python2.7/site-packages/mock.py", line 1027, in _mock_call
      ret_val = effect(*args, **kwargs)
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/system.py", line 37, in _filter_system_call
      return real_call_function(command)
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/system.py", line 924, in call
      raise exc
  OSError: lsof -wnP -iTCP -sTCP:LISTEN returned exit status 1

  ======================================================================
  ERROR: test_pid_by_port_netstat
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/system.py", line 274, in test_pid_by_port_netstat
      self.assertEquals(tor_pid, stem.util.system.pid_by_port(test.runner.CONTROL_PORT))
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/system.py", line 471, in pid_by_port
      results = call(GET_PID_BY_PORT_NETSTAT, None)
    File "/usr/lib64/python2.7/site-packages/mock.py", line 964, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/usr/lib64/python2.7/site-packages/mock.py", line 1027, in _mock_call
      ret_val = effect(*args, **kwargs)
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/system.py", line 37, in _filter_system_call
      return real_call_function(command)
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/system.py", line 924, in call
      raise exc
  OSError: netstat -npltu returned exit status 255

  ======================================================================
  FAIL: test_pid_by_port
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/system.py", line 244, in test_pid_by_port
      self.assertEquals(tor_pid, stem.util.system.pid_by_port(tor_port))
  AssertionError: 25297 != None

  ----------------------------------------------------------------------