Proc unit testing failure under python3
Simple bytes/unicode error in our tests. This caused a couple proc tests to
fail under python3...

  ======================================================================
  ERROR: test_connections_ipv6
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/proc.py", line 370, in connections
      with open(proc_file_path, 'rb') as proc_file:
    File "/usr/local/lib/python3.2/dist-packages/mock/mock.py", line 1062, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/usr/local/lib/python3.2/dist-packages/mock/mock.py", line 1128, in _mock_call
      ret_val = effect(*args, **kwargs)
    File "/home/atagar/Desktop/stem/test/unit/util/proc.py", line 262, in <lambda>
      '/proc/net/tcp': io.BytesIO(''),
  TypeError: 'str' does not support the buffer interface