Test failure when cryptography module unavailable
Simply missing a requirement check...

  ======================================================================
  ERROR: test_validate_signatures_incorrect_digests
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/networkstatus/document_v3.py", line 1365, in test_validate_signatures_incorrect_digests
      from cryptography.hazmat.backends import default_backend
  ImportError: No module named cryptography.hazmat.backends