Fixing regression from previous DirectoryAuthority change
Shame on me. What good are tests if you don't run 'em?

  Traceback (most recent call last):
    File "./run_tests.py", line 467, in <module>
      main()
    File "./run_tests.py", line 216, in main
      for test_class in test.util.get_unit_tests(args.specific_test):
    File "/home/atagar/Desktop/stem/test/util.py", line 125, in _get_tests
      module = __import__(module_name)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/remote.py", line 10, in <module>
      import stem.descriptor.remote
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 674, in <module>
      v3ident = 'D586D18309DED4CD6D57C18FDB97EFA96D330566',
  TypeError: __init__() got an unexpected keyword argument 'is_bandwidth_authority'