test_shorthand_aliases integ test broken
Our unit tests caused us to cache a Mock object rather than a
DescriptorDownloader for our singleton. This in turn broke our later integ
tests...

  ======================================================================
  ERROR: test_shorthand_aliases
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/runner.py", line 161, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/runner.py", line 178, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 31, in test_shorthand_aliases
      desc = list(stem.descriptor.remote.get_server_descriptors('9695DFC35FFEB861329B9F1AB04C46397020CE31').run())[0]
  IndexError: list index out of range