Fix couple online integ tests
We don't run tests requiring our ONLINE target by default so they get a little less love. Fixing the following couple...

  ======================================================================
  FAIL: test_authorities_are_up_to_date
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/runner.py", line 161, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/runner.py", line 178, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 38, in test_authorities_are_up_to_date
      self.fail("%s isn't a recognized directory authority in stem" % auth.nickname)
  AssertionError: dannenberg-legacy isn't a recognized directory authority in stem

  ----------------------------------------------------------------------

  ======================================================================
  FAIL: test_attributes
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/manual.py", line 198, in test_attributes
      assert_equal('commandline options', EXPECTED_CLI_OPTIONS, set(manual.commandline_options.keys()))
    File "/home/atagar/Desktop/stem/test/integ/manual.py", line 190, in assert_equal
      self.fail("Changed tor's man page? The %s changed as follows...\n\nexpected: %s\n\nactual: %s" % (category, expected, actual))
  AssertionError: Changed tor's man page? The commandline options changed as follows...

  expected: set(['-f FILE', '--ignore-missing-torrc', '--list-fingerprint', '--defaults-torrc FILE', '--allow-missing-torrc', '--nt-service', '--verify-config', '--service remove|start|stop', '--quiet|--hush', '--list-torrc-options', '--service install [--options command-line options]', '--version', '--hash-password PASSWORD', '-h, -help'])

  actual: set([u'-f FILE', u'--hash-password PASSWORD', u'--ignore-missing-torrc', u'--list-fingerprint', u'--defaults-torrc FILE', u'--allow-missing-torrc', u'--nt-service', u'--verify-config', u'--service remove|start|stop', u'--keygen [--newpass]', u'--list-torrc-options', u'--service install [--options command-line options]', u'--quiet|--hush', u'--version', u'-h, -help'])

I'm still getting a couple other failures but one is from #17913 and the rest
are spurious.