Revert use of CONF_CHANGED events by test_reattaching_listeners
Reverting part of the change for #14943 and reopening the ticket since this is
causing frequent Jenkins failures...

  ======================================================================
  FAIL: test_reattaching_listeners
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/runner.py", line 127, in wrapped
      return func(self, *args, **kwargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/control/controller.py", line 273, in test_reattaching_listeners
      self.assertTrue(event_notice.wait(10))
  AssertionError: False is not true

  ----------------------------------------------------------------------
  Ran 37 tests in 11.423s

Test passes more often that not but at this point the cure is worse than the
disease, so we should revert until this can be addressed.