Empty hidden services are invalid
Tor added some more validation for the hidden service configuration...

  https://trac.torproject.org/projects/tor/ticket/20860

This broke our integ tests...

  ======================================================================
  ERROR: test_hidden_services_conf
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/runner.py", line 127, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 549, in test_hidden_services_conf
      controller.set_hidden_service_conf(initialconf)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2582, in set_hidden_service_conf
      self.set_options(hidden_service_options)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2419, in set_options
      raise stem.InvalidRequest(response.code, response.message)
  InvalidRequest: Unacceptable option value: Failed to configure rendezvous options. See logs for details.

  ----------------------------------------------------------------------

Reproing this with the tor-prompt the log says...

  WARN Hidden service ("/tmp/hs_dir") with no ports configured.

That's fine. This isn't what we were testing anyway.