Skip tests requiring setUpClass() in python 2.6
Unittest's setUpClass() function was added in python 2.7, so skipping tests
that require it when running python 2.6.

  ======================================================================
  ERROR: test_installs_all_files
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/installation.py", line 74, in test_installs_all_files
      if self.requires_installation():
    File "/home/atagar/Desktop/stem/test/integ/installation.py", line 48, in requires_installation
      if self.skip_reason:
  AttributeError: 'TestInstallation' object has no attribute 'skip_reason'

  ----------------------------------------------------------------------
  Ran 2 tests in 0.002s

  FAILED (errors=2)