Fix datetime_to_unix() for python 2.6
Datetime's total_seconds() method was added in python 2.7. I'm a tad unsure why
I need an hour offset for this workaround but meh. Not timezones, so guess I'm
just missing some off-by-one error.

  ======================================================================
  ERROR: test_datetime_to_unix
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/util/__init__.py", line 24, in test_datetime_to_unix
      self.assertEqual(1344251971.0, datetime_to_unix(datetime.datetime(2012, 8, 6, 11, 19, 31)))
    File "/home/atagar/Desktop/stem/stem/util/__init__.py", line 37, in datetime_to_unix
      return (timestamp - datetime.datetime(1970, 1, 1)).total_seconds()
  AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

  ----------------------------------------------------------------------
  Ran 1 test in 0.001s

  FAILED (errors=1)