Missing is_available() mocks for unit tests
Our jenkins tests are presently failing in quite a few ways. First addressing
some of the easiest ones about a2x not being present...

  ======================================================================
  ERROR: test_download_man_page_when_successful
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/mock.py", line 1224, in patched
      return func(*args, **keywargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/manual.py", line 214, in test_download_man_page_when_successful
      stem.manual.download_man_page(file_handle = output)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/manual.py", line 196, in download_man_page
      raise IOError('We require a2x from asciidoc to provide a man page')
  IOError: We require a2x from asciidoc to provide a man page

  ======================================================================
  FAIL: test_download_man_page_when_a2x_fails
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/mock.py", line 1224, in patched
      return func(*args, **keywargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/manual.py", line 197, in test_download_man_page_when_a2x_fails
      self.assertEqual("Unable to run 'a2x -f manpage /no/such/path/tor.1.txt': call failed", str(exc))
  AssertionError: "Unable to run 'a2x -f manpage /no/such/path/tor.1.txt': call failed" != 'We require a2x from asciidoc to provide a man page'

  ======================================================================
  FAIL: test_download_man_page_when_download_fails
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/mock.py", line 1224, in patched
      return func(*args, **keywargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/manual.py", line 185, in test_download_man_page_when_download_fails
      self.assertEqual("Unable to download tor's manual from https://www.atagar.com/foo/bar to /no/such/path/tor.1.txt: <urlopen error <urlopen error [Errno -2] Name or service not known>>", str(exc))
  AssertionError: "Unable to download tor's manual from https://www.atagar.com/foo/bar to /no/such/path/tor.1.txt: <urlopen error <urlopen error [Errno -2] Name or service not known>>" != 'We require a2x from asciidoc to provide a man page'

  ======================================================================
  FAIL: test_download_man_page_when_unable_to_write
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/mock.py", line 1224, in patched
      return func(*args, **keywargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/manual.py", line 174, in test_download_man_page_when_unable_to_write
      self.assertEqual("Unable to download tor's manual from https://gitweb.torproject.org/tor.git/plain/doc/tor.1.txt to /no/such/path/tor.1.txt: unable to write to file", str(exc))
  AssertionError: "Unable to download tor's manual from https://gitweb.torproject.org/tor.git/plain/doc/tor.1.txt to /no/such/path/tor.1.txt: unable to write to file" != 'We require a2x from asciidoc to provide a man page'