Ignore vim swap files for installation integ test
We have a new test that asserts that everything in the stem directory gets
installed. Vim swap files are an obvious exception - ignoring those...

  ======================================================================
  FAIL: test_installs_all_files
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/installation.py", line 93, in test_installs_all_files
      self.fail("The following files were expected to be in our installation but weren't. Maybe our setup.py needs to be updated?\n\n%s" % '\n'.join(missing))
  AssertionError: The following files were expected to be in our installation but weren't. Maybe our setup.py needs to be updated?

  stem/.manual.py.swp

  ----------------------------------------------------------------------
  Ran 2 tests in 0.432s