launch_tor() raisesd a ValueError when outside the main thread
When outside the main thread signal raises...

  ValueError: signal only works in main thread

To account for this doing two things...

  * If the user doesn't specify a timeout then dropping it when outside the
    main thread to avoid erroring. This is similar to what we do on Windows
    (which doesn't support signal either).

  * If the user explicitly specifies a timeout then providing a more useful
    error message.

Caught thanks to an anonymous user.