Missing bytes conversion for test data
======================================================================
ERROR: test_event_handling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/runner.py", line 127, in wrapped
    return func(self, *args, **kwargs)
  File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 161, in test_event_handling
    controller.set_conf('NodeFamily', random_fingerprint())
  File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 50, in random_fingerprint
    return hashlib.sha1(str(time.time())).hexdigest().upper()
TypeError: Unicode-objects must be encoded before hashing

----------------------------------------------------------------------