Check for /proc read permissions when determining if it's available
On Gentoo proc permissions are locked down, causing our tests to fail...

  ======================================================================
  ERROR: test_get_connections
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/test/integ/util/connection.py", line 27, in test_get_connections
      connections = get_connections(resolver, process_pid = tor_pid)
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/connection.py", line 177, in get_connections
      return [Connection(*conn) for conn in stem.util.proc.connections(process_pid)]
    File "/var/tmp/portage/net-libs/stem-1.2.2_p20141208/work/stem-1.2.2_p20141208/stem/util/proc.py", line 404, in connections
      raise exc
  IOError: unable to read '/proc/net/tcp': [Errno 13] Permission denied: '/proc/net/tcp'

  ----------------------------------------------------------------------

I'm tempted to change our 'is proc available?' check, but the platform only
restricts /proc/net/*, so only doing this for connection resolution.