Add missing assertItemsEqual() for python 2.6
Ok, that does it. Rather than avoiding use of methods on python 2.6 gonna add
them when simple to do so. Since our last release we've started using
assertItemsEqual. This wasn't available back then so adding it.

  ======================================================================
  ERROR: test_votes_by_bandwidth_authorities
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python2.6/dist-packages/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/tutorial_examples.py", line 311, in test_votes_by_bandwidth_authorities
      self.assert_equal_unordered(VOTES_BY_BANDWIDTH_AUTHORITIES_OUTPUT, stdout_mock.getvalue())
    File "/home/atagar/Desktop/stem/test/unit/tutorial_examples.py", line 141, in assert_equal_unordered
      self.assertItemsEqual(expected.splitlines(), actual.splitlines())
  AttributeError: 'TestTutorialExamples' object has no attribute 'assertItemsEqual'

  ----------------------------------------------------------------------
  Ran 6 tests in 0.255s