Missing list wrapper causing stacktraces during controller shutdown
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/atagar/Desktop/stem/stem/control.py", line 848, in _reader_loop
    control_message = self._socket.recv()
  File "/home/atagar/Desktop/stem/stem/socket.py", line 174, in recv
    self.close()
  File "/home/atagar/Desktop/stem/stem/socket.py", line 296, in close
    self._close()
  File "/home/atagar/Desktop/stem/stem/control.py", line 763, in _close
    self._notify_status_listeners(State.CLOSED)
  File "/home/atagar/Desktop/stem/stem/control.py", line 813, in _notify_status_listeners
    self._state_change_threads.append(notice_thread)
AttributeError: 'filter' object has no attribute 'append'