'extra-info-digest line had an invalid value' from additions in proposal 228
Proposal 228 adds additional content to the extra-info-digest line of server
descriptors, causing validation to fail with...

  ValueError: extra-info-digest line had an invalid value (should be 40 hex
  characters): extra-info-digest 0879DB7B765218D7B3AE7557669D20307BB21CAA
  V609l+N6ActBveebfNbH5lQ6wHDNstDkFgyqEhBHwtA

Honestly Stem is probably being a bit too strict here. Following is tracking
spec clarifications...

  https://trac.torproject.org/projects/tor/ticket/16227

And as for proposal 228 itself awaiting its dir-spec addition...

  https://trac.torproject.org/projects/tor/ticket/16235