Additional information when stem.util.system.call() fails
Commonly callers at least want the stderr. I ran into this because our
cache_manual.py error output sucked...

  IOError: Unable to run 'a2x -f manpage /tmp/tmpU36UMJ/tor.1.txt': a2x -f
  manpage /tmp/tmpU36UMJ/tor.1.txt returned exit status 1

This says the command twice, and gives no useful informaiton about what the
error even is. Now it's...

  IOError: Unable to run 'a2x -f manpage /tmp/tmpfq6cVA/tor.1.txt': a2x: ERROR:
  /usr/bin/asciidoc --backend docbook -a a2x-format=manpage  --doctype manpage
  --out-file /tmp/tmpfq6cVA/tor.1.xml /tmp/tmpfq6cVA/tor.1.txt returned
  non-zero exit status 1